### ISSUE TITLE
figure2

### ISSUE THREAD

**Issue by a-drop-in-the-ocean456** [zimoqingfeng/UMOP#3]
hello,this paper is a very nice work,I am interested in how to draw these figures in figure 2 of this paper,thank you.
![IMG_20210921_001449](https://user-images.githubusercontent.com/72304708/134037549-59906653-27b1-44f2-b1c5-16bffa614bd4.jpg)

**Comment by liang532** [comment]
![Uploading IMG_20210921_001449.jpg…]()

**Comment by zimoqingfeng** [comment]
During training, we generate logs for recording "the number of total valid samples" and "the number of positive samples" in each level, and then draw a box polt according to their proportions.

More details in
https://github.com/zimoqingfeng/UMOP/blob/master/mmdet/models/dense_heads/anchor_head.py#L417
https://github.com/zimoqingfeng/UMOP/blob/master/mmdet/models/dense_heads/fcos_head.py#L229
https://github.com/zimoqingfeng/UMOP/blob/master/mmdet/models/dense_heads/vfnet_head.py#L394

**Comment by a-drop-in-the-ocean456** [comment]
thank you for your answer.
