### ISSUE TITLE
For YOLO

### ISSUE THREAD

**Issue by qdd1234** [zimoqingfeng/UMOP#5]
Hi, thanks for your wonderful work, I want to ask whether UMOP is suitable for YOLO? I want to apply the UMOP to YOLOX. The YOLOX head is shown in the picture.
![image](https://user-images.githubusercontent.com/68497831/134914737-630bf71a-3f45-4c9a-9c32-c9e7dfd1f26c.png)

**Comment by zimoqingfeng** [comment]
YOLOX is a nice work based on OTA and YOLO series. Maybe you could try our Progressive Focal Loss for object classification.
