### ISSUE TITLE
Question about code in dense-head

### ISSUE THREAD

**Issue by Senwang98** [zimoqingfeng/UMOP#6]
Hi, @zimoqingfeng 
Thank you for your work, I am intereseted in it.
I try to use your idea to improve my own detection performance. 
I met some problems.
In line https://github.com/zimoqingfeng/UMOP/blob/16af670ee10b95015296d4a8da56a10fb7b89f72/mmdet/models/dense_heads/level_resampling_head.py#L94, for example my label=3, my num_classes=3, so in this way, i will always get y=[0,0,0,0,].
Do you think I need to modify [:, :self.num_classes] to [:, :self.num_classes+1]?

**Comment by zimoqingfeng** [comment]
Thanks for your attention.
In our code, "self.num_classes" do not contain the background class, i.e., we set 80 for COCO dataset.

For num_classes=3 and labels=0, we got y=[0,0,0].
For num_classes=3 and labels=3, we got y=[0,0,1].
