### ISSUE TITLE
Is UMOP suitable for light-weight detector?

### ISSUE THREAD

**Issue by Senwang98** [zimoqingfeng/UMOP#7]
Hi, @zimoqingfeng 
Recently, I am doing some work about light-weight detection. I try to use your idea of pfl to help improving detection performance, but it seem that this idea is not suitable for such condition. 
Have you test such light-weight backbone before(such as mobilev2 or shufflenetv2 and etc.)? It may be fun since light-weight is more useful in many applications.
Wishing for your reply.

**Comment by zimoqingfeng** [comment]
Thanks for your attention. For tiny detectors, pfl is not very competitive on COCO, as an individual component. We are still to study this aspect continuelly.
On the other hand, a more appropriate benchmark may be recommended. We sincerely hope this suggestion is helpful for you.

**Comment by Senwang98** [comment]
@zimoqingfeng 
Okay, UMOP brings performance decreasement in light-weight detector.
Maybe the level imblance is not very serious in light-weight detector.
